#!/usr/bin/env node

/**
* Pseudo-cli
*/
var tracker = require('./lib/tracker'),
    fs = require('fs'),
    argv = require('optimist')
              .usage('Usage: $0 --config config.json')
              .demand(['config'])
              .argv;

tracker(JSON.parse(fs.readFileSync('./' + (argv.config))));
